services:
    postgresql:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        ports:
            - "5432:5432" 


    dggstools:
        image: dggstools
        build:
            context: backend/services/dggstools
            dockerfile: Dockerfile


    backend:
        image: backend
        build:
            context: backend/
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        depends_on:
            - postgresql

    www:
        image: www
        build:
            context: frontend/
            dockerfile: Dockerfile
        ports:
            - "80:80"

    k6:
        image: grafana/k6
        volumes:
        - ./backend/tests:/scripts
        depends_on:
        - backend
        stdin_open: true
        tty: true


volumes:
    postgresql-data:
