services:
    postgresql:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        ports:
            - "5432:5432" 
        restart: always


    dggstools:
        image: dggstools
        build:
            context: services/dggstools
            dockerfile: Dockerfile
        restart: always


    backend:
        image: backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        depends_on:
            - postgresql
        restart: always


volumes:
    postgresql-data: