export const { VITE_GOOGLE_OAUTH_CLIENT_ID:GOOGLE_OAUTH_CLIENT_ID, VITE_BACKEND_API_URL:BACKEND_API_URL } = import.meta.env;

console.log({ VITE_GOOGLE_OAUTH_CLIENT_ID:GOOGLE_OAUTH_CLIENT_ID, VITE_BACKEND_API_URL:BACKEND_API_URL });